name: gallery_image_viewer
description: An easy image viewer with pinch & zoom, multi image, gallery image and built-in full-screen dialog support.
version: 1.2.0
homepage: https://github.com/SEMAJdev/gallery_image_viewer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_expandable_fab: ^2.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
